version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_DB=vapor
      - POSTGRES_USER=vapor
      - POSTGRES_PASSWORD=password
  mysql:
    image: "mysql/mysql-server:5.7"
    environment:
      - MYSQL_USER=vapor
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=vapor
  redis:
    image: "redis"
  til-users:
    depends_on:
      - postgres
      - redis
    build:
      context: ./TILAppUsers
      dockerfile: web.Dockerfile
    environment:
      - DATABASE_HOSTNAME=postgres
      - REDIS_HOSTNAME=redis
      - PORT=8081
      - ENVIRONMENT=production
      - DATABASE_PASSWORD=password
  til-acronyms:
    depends_on:
      - mysql
      - til-users
    build:
      context: ./TILAppAcronyms
      dockerfile: web.Dockerfile
    environment:
      - DATABASE_HOSTNAME=mysql
      - PORT=8082
      - ENVIRONMENT=production
      - AUTH_HOSTNAME=til-users
  til-api:
    depends_on:
      - til-users
      - til-acronyms
    ports:
      - "8080:8080"
    build:
      context: ./TILAppAPI
      dockerfile: web.Dockerfile
    environment:
      - USERS_HOSTNAME=til-users
      - ACRONYMS_HOSTNAME=til-acronyms
      - PORT=8080
      - ENVIRONMENT=production
